### ISSUE TITLE
Invalid package.json in package.json

### ISSUE THREAD

**Issue by lukewowo** [papra-hq/papra-website#21]
Have recently upgraded my docker container from the docker release: "Created": "2025-04-16T18:08:50.75734481Z", to the latest "Created": "2025-05-14T11:22:47.898375411Z".

Now when doing a docker compose up, a bunch of errors appear, I can't see anywhere to find this package.json.

Reverting back to the previous image `ghcr.io/papra-hq/papra@sha256:a022e106b16a8285c32762c94976fe86db02838ed80a7e98b6ed9bbc744fb9c5` works.

```
~/papra$ docker compose up
[+] Running 1/1
 ✔ Container papra  Created                                                                                                                     0.0s 
Attaching to papra
papra  | Invalid package.json in package.json
papra exited with code 1
papra  | Invalid package.json in package.json
papra exited with code 1
papra  | Invalid package.json in package.json
papra exited with code 1
papra  | Invalid package.json in package.json
```

my docker-compose.yml file is as follows

```
services:
  papra:
    container_name: papra
    image: ghcr.io/papra-hq/papra:latest
    restart: unless-stopped
    ports:
      - "1221:1221"
    volumes:
      - ./app-data:/app/app-data
    user: "1000:1000"
    environment:
      CLIENT_BASE_URL: "https://papra.domain"
      CLIENT_OAUTH_REDIRECT_URL: "https://papra.domain/confirm"
      SERVER_BASE_URL: "https://papra.domain"
      TRUSTED_ORIGINS: "https://papra.domain"
      SERVER_CORS_ORIGINS: "https://papra.domain"
```
